name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Set up the specified Xcode version
      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'   # Specify the Xcode version needed

      # 3. Install dependencies using CocoaPods, Carthage, or Swift Package Manager if needed
      - name: Install dependencies
        run: |
          brew install cocoapods || true   # Example with CocoaPods, adjust for your dependency manager
          pod install

      # 4. Build and run tests
      - name: Build and Test
        run: xcodebuild -scheme "YourScheme" -destination 'platform=iOS Simulator,name=iPhone 14' test
